<?php
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../includes/auth.php';
if (function_exists('verifier_role')) { verifier_role('enseignant'); }
$id_enseignant = $_SESSION['id_enseignant'] ?? 1;
$message = ""; $erreur = "";
if (isset($_POST['enregistrer_notes'])) {
    $id_cours = intval($_POST['id_cours']);
    foreach ($_POST['notes'] as $id_etudiant => $notes) {
        $id_etudiant = intval($id_etudiant); $note_controle = floatval($notes['note_controle']); $note_exam = floatval($notes['note_exam']); $note_projet = floatval($notes['note_projet']); $moyenne = ($note_controle + $note_exam + $note_projet) / 3;
        $stmt_existe = mysqli_prepare($conn, "SELECT id_note, validee FROM note WHERE id_etudiant = ? AND id_cours = ?"); mysqli_stmt_bind_param($stmt_existe, "ii", $id_etudiant, $id_cours); mysqli_stmt_execute($stmt_existe); $note_existante = mysqli_fetch_assoc(mysqli_stmt_get_result($stmt_existe));
        if ($note_existante && intval($note_existante['validee']) === 1) { continue; }
        if ($note_existante) { $stmt_update = mysqli_prepare($conn, "UPDATE note SET note_controle = ?, note_exam = ?, note_projet = ?, moyenne = ?, date_saisie = NOW() WHERE id_note = ?"); mysqli_stmt_bind_param($stmt_update, "ddddi", $note_controle, $note_exam, $note_projet, $moyenne, $note_existante['id_note']); mysqli_stmt_execute($stmt_update); }
        else { $stmt_insert = mysqli_prepare($conn, "INSERT INTO note (note_controle, note_exam, note_projet, moyenne, validee, date_saisie, id_etudiant, id_cours) VALUES (?, ?, ?, ?, 0, NOW(), ?, ?)"); mysqli_stmt_bind_param($stmt_insert, "ddddii", $note_controle, $note_exam, $note_projet, $moyenne, $id_etudiant, $id_cours); mysqli_stmt_execute($stmt_insert); }
    }
    $message = "Notes enregistrées avec succès.";
}
include __DIR__ . '/../includes/header.php';
?>
<main class="container"><h1>Saisie des notes</h1><?php if ($message): ?><p class="success"><?php echo htmlspecialchars($message); ?></p><?php endif; ?><?php if ($erreur): ?><p class="error"><?php echo htmlspecialchars($erreur); ?></p><?php endif; ?>
<?php $id_cours = isset($_GET['id_cours']) ? intval($_GET['id_cours']) : (isset($_POST['id_cours']) ? intval($_POST['id_cours']) : 0); $stmt_cours = mysqli_prepare($conn, "SELECT id_cours, code_cours, titre FROM cours WHERE id_enseignant = ? ORDER BY code_cours"); mysqli_stmt_bind_param($stmt_cours, "i", $id_enseignant); mysqli_stmt_execute($stmt_cours); $cours_result = mysqli_stmt_get_result($stmt_cours); ?>
<form method="get" action="notes.php" class="form-card"><label for="id_cours">Choisir un cours</label><select name="id_cours" id="id_cours" required><option value="">Sélectionner un cours</option><?php while ($cours = mysqli_fetch_assoc($cours_result)): ?><option value="<?php echo $cours['id_cours']; ?>" <?php if ($id_cours == $cours['id_cours']) echo 'selected'; ?>><?php echo htmlspecialchars($cours['code_cours'] . ' - ' . $cours['titre']); ?></option><?php endwhile; ?></select><button type="submit">Afficher</button></form>
<?php if ($id_cours > 0): ?><?php $sql = "SELECT etudiant.id_etudiant, utilisateur.nom, utilisateur.prenom, note.note_controle, note.note_exam, note.note_projet, note.moyenne, note.validee FROM inscription INNER JOIN etudiant ON inscription.id_etudiant = etudiant.id_etudiant INNER JOIN utilisateur ON etudiant.id_user = utilisateur.id_user LEFT JOIN note ON note.id_etudiant = etudiant.id_etudiant AND note.id_cours = inscription.id_cours WHERE inscription.id_cours = ? ORDER BY utilisateur.nom, utilisateur.prenom"; $stmt = mysqli_prepare($conn, $sql); mysqli_stmt_bind_param($stmt, "i", $id_cours); mysqli_stmt_execute($stmt); $etudiants = mysqli_stmt_get_result($stmt); ?><form method="post" action="notes.php"><input type="hidden" name="id_cours" value="<?php echo $id_cours; ?>"><table><thead><tr><th>Étudiant</th><th>Note contrôle</th><th>Note exam</th><th>Note projet</th><th>Moyenne</th><th>Validation</th></tr></thead><tbody><?php if ($etudiants && mysqli_num_rows($etudiants) > 0): while ($etu = mysqli_fetch_assoc($etudiants)): $disabled = $etu['validee'] ? 'disabled' : ''; ?><tr><td><?php echo htmlspecialchars($etu['prenom'] . ' ' . $etu['nom']); ?></td><td><input type="number" step="0.01" min="0" max="20" name="notes[<?php echo $etu['id_etudiant']; ?>][note_controle]" value="<?php echo htmlspecialchars($etu['note_controle'] ?? ''); ?>" <?php echo $disabled; ?>></td><td><input type="number" step="0.01" min="0" max="20" name="notes[<?php echo $etu['id_etudiant']; ?>][note_exam]" value="<?php echo htmlspecialchars($etu['note_exam'] ?? ''); ?>" <?php echo $disabled; ?>></td><td><input type="number" step="0.01" min="0" max="20" name="notes[<?php echo $etu['id_etudiant']; ?>][note_projet]" value="<?php echo htmlspecialchars($etu['note_projet'] ?? ''); ?>" <?php echo $disabled; ?>></td><td><?php echo isset($etu['moyenne']) ? number_format($etu['moyenne'], 2) : '-'; ?></td><td><?php echo $etu['validee'] ? 'Validée' : 'Non validée'; ?></td></tr><?php endwhile; else: ?><tr><td colspan="6">Aucun étudiant inscrit à ce cours.</td></tr><?php endif; ?></tbody></table><button type="submit" name="enregistrer_notes">Enregistrer les notes</button></form><?php endif; ?></main><?php include __DIR__ . '/../includes/footer.php'; ?>
